name: adminlaporanwarga
description: Admin Dashboard untuk Laporan Infrastruktur
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase for backend
  supabase_flutter: ^2.3.0

  # UI & Fonts
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.6

  # State Management (optional)
  provider: ^6.1.1
  csv: ^5.1.1
  excel: ^4.0.3
  pdf: ^3.10.7
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets (if needed)
  # assets:
  #   - assets/images/
  #   - assets/icons/